<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>JyotiIyerCPA</RootNamespace>
    <UserSecretsId>3bc687f2-6e76-4c7d-ac76-da8a89459bca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="SendGrid" Version="9.29.1" />
  </ItemGroup>

  <!-- Exclude tool sources from web project compilation -->
  <ItemGroup>
    <Compile Remove="Tools\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

</Project>
